language: cpp
dist: bionic
os:
  - linux

jobs:
  include:
    stage: Test
    name: "Test"
    before_install:
      # Setting Environment
      - git config --global --unset user.password
      - git config --global --unset user.name
      - git config --global --unset user.email
      
      - git config --global --add user.name $USEREMAIL
      - git config --global --add user.email $USEREMAIL
      - git config --global --add user.password $PASSWORD
      - git clone $GIT_HTTPS
      - cd macro-commit-repository
    script:
      - echo $(TZ=":Asia/Seoul" date '+%Y--%m--%d_%H:%M:%S') >> commit.txt
      - git add .
      - git commit -m $(TZ=":Asia/Seoul" date '+%Y--%m--%d_%H:%M:%S')
      - git push origin master
