language: cpp
dist: bionic
os:
  - linux

jobs:
  include:
    stage: Test
    name: "Test"
    before_install:
      # Setting Environment
      - git clone $GIT_HTTPS -q
      - cd macro-commit-repository
      - git init -q
    script:
      - echo $(TZ=":Asia/Seoul" date '+%Y--%m--%d_%H:%M:%S') >> commit.txt
      - git add .
      - git commit -m $(TZ=":Asia/Seoul" date '+%Y--%m--%d_%H:%M:%S')
      - git remote add origin "github.com/ounols/macro-commit-repository.git"
      - git push -u origin master
