language: cpp
dist: bionic
os:
  - linux

jobs:
  include:
    stage: Test
    name: "Test"
    before_install:
      # Setting Environment
      - git clone $GIT_HTTPS -q
      - cd macro-commit-repository
      - git init -q
    script:
      - echo $(TZ=":Asia/Seoul" date '+%Y--%m--%d_%H:%M:%S') >> commit.txt
      - ls
      - git add commit.txt
      - git commit -m "asdf"
      - git config user.name $USERNAME
      - git config user.email $USERMAIL
      - git config user.password $PASSWORD
      - git push -u origin master
