language: cpp
dist: bionic
os:
  - linux

jobs:
  include:
    stage: Test
    name: "Test"
    before_install:
      # Setting Environment
      - sudo apt-get update
      - git config --global user.name $USERNAME
      - git config --global user.email $USEREMAIL
      - git config --global user.password $PASSWORD
      - git clone $GIT_HTTPS
      - cd macro-commit-repository
    script:
      - echo $(TZ=":Asia/Seoul" date '+%Y--%m--%d_%H:%M:%S') >> commit.txt
      - git add .
      - git commit -m $(TZ=":Asia/Seoul" date '+%Y--%m--%d_%H:%M:%S')
      - git push origin master
