language: cpp
dist: bionic
os:
  - linux
jobs:
  include:
    stage: Test
    name: "Test"
    before_install:
      # Setting Environment
      - git clone $GIT_HTTPS -q
    script:
      - chmod +x script.sh
      - ./script.sh
